server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie
microservoice-provider-user:
  ribbon:
    #脱离eureka时的ribbon配置要使用以下属性指定具体的服务提供者地址
    listOfServers: localhost:8000,localhost:8001