server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yunlongZ163/spring-cloud-config-repo.git
          search-paths: configfile
          username: yunlongz163@163.com
          password: qq18501671431
        health:
          repositories:
            a-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev

#配置git的健康检查