server:
  port: 8000
  context-path: /provider
spring:
  application:
    name: microservice-provider-user
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: debug
    #org.springframework.web.servlet.DispatcherServlet: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instances:
    prefer-ip-address: true