server:
  port: 8762
logging:
  level:
    root: INFO
eureka:
  client:
    #是否将自己注册到eureka
    #register-with-eureka: false
    #是否从eureka获取注册信息
    #fetch-registry: false
    #设置eureka的交互地址
    serviceUrl:
      #将自己注册到peer2这个Eureka上面去
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: peer2
spring:
  application:
    name: microservice-discovery-eureka-ha